/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import birdScene from "../assets/3d/bird.glb";
import { a } from "@react-spring/three";

const Bird = () => {
    const {scene, animations} = useGLTF(birdScene);
    return (
        <mesh position={[-5, 2, 1]} scale={[0.003, 0.003, 0.003]}>
            <primitive object={scene} />
        </mesh>
    )
};

export default Bird;
